name: Verify
on:
  pull_request:
  push:
    branches: [master, main]
permissions:
  contents: read
jobs:
  verify:
    strategy:
      matrix:
        os: [windows-2025, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: maven
      - name: Verify Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: ./build.ps1
      - name: Verify macOS
        if: runner.os == 'macOS'
        run: bash ./build.sh
